### ISSUE TITLE
Selectpicker is not a function

### ISSUE THREAD

**Issue by henslecd** [emonney/QuickApp#38] opened 2017-10-17 02:30 UTC
I am getting this js error when going to Settings -> Preferences.  The alert prompts 6 or 7 times and makes all selections unusable.

ERROR TypeError: __WEBPACK_IMPORTED_MODULE_1_jquery__(...).selectpicker is not a function
    at BootstrapSelectDirective.ngOnInit (main-client.js:6874)
    at checkAndUpdateDirectiveInline (vendor.js:15593)
    at checkAndUpdateNodeInline (vendor.js:17094)
    at checkAndUpdateNode (vendor.js:17033)
    at debugCheckAndUpdateNode (vendor.js:17894)
    at debugCheckDirectivesFn (vendor.js:17835)
    at Object.eval [as updateDirectives] (ng:///AppModule/UserPreferencesComponent.ngfactory.js:672)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.js:17820)
    at checkAndUpdateView (vendor.js:17000)
    at callViewAction (vendor.js:17365)

**Comment by emonney** [comment] 2017-12-05 05:55
What version of QuickApp are you using?
Can you share your package.json file?

**Comment by emonney** [comment] 2017-12-12 11:11
I couldn't reproduce this error.
Closing ticket.
If this is still an issue reopen the ticket with the steps to reproduce it.

**Closed by emonney** 2017-12-12 11:11 UTC
