### ISSUE TITLE
After switching to .netcore 2.2  'ResponseCacheAttribute' cannot be applied to Razor Page handler methods. It may be applied either to the Razor Page model or applied globally.

### ISSUE THREAD

**Issue by IngoManthey** [emonney/QuickApp#126] opened 2019-01-25 14:02 UTC
Hi,
I get the follow  warning MVC1001: 'ResponseCacheAttribute' cannot be applied to Razor Page handler methods. It may be applied either to the Razor Page model or applied globally.

what can I do?

regards Ingo

**Comment by emonney** [comment] 2019-03-04 16:25
If this is related to this issue: https://github.com/aspnet/templating/issues/563 then it should be fixed with the latest update.
Otherwise paste the full stack trace here so we can trace the root cause

**Closed by emonney** 2019-03-04 16:25 UTC
